name: Manual Dispatch Workflow

on:
  workflow_dispatch:

jobs:
  run-makefile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run makefile command
      run: make dots